#!/usr/bin/env python3
"""Generate Gen-3 (Ruby/Sapphire/Emerald) name tables as a committed C blob.

The save stores the *internal* Gen-3 species index, the standard move id, and
the standard item id. This script pulls the canonical name lists straight from
the pret/pokeemerald decomp (which keeps the original ROM ordering, so the
designated-initializer file order == numeric id order) and emits three flat
tables:

  source/gen3_names.{c,h}
    gen3_species_name(internal_species)   internal index 0..411 -> NAME
    gen3_move_name(move_id)               move id 0..354       -> NAME
    gen3_item_name(item_id)               item id 0..376        -> NAME

All strings land in ROM (.rodata); zero EWRAM cost. The generated .c is
committed, so the firmware build never needs network or this script.

Run from the repo root:  python3 tools/gen_names.py
"""
import os, re, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_C = os.path.join(ROOT, "source", "gen3_names.c")
OUT_H = os.path.join(ROOT, "source", "gen3_names.h")

# pret/pokeemerald keeps the original internal species ordering (Treecko=277,
# Kyogre=404, the five displaced legendaries at 407..411), so file order is
# exactly what the save stores. Pinned to master; swap for a commit to freeze.
BASE = "https://raw.githubusercontent.com/pret/pokeemerald/master/src/data"
SRC = {
    "species": BASE + "/text/species_names.h",
    "moves":   BASE + "/text/move_names.h",
    "items":   BASE + "/items.h",
}
CACHE = os.path.join(os.path.dirname(__file__), "_namecache")


def fetch(key):
    os.makedirs(CACHE, exist_ok=True)
    local = os.path.join(CACHE, key + ".h")
    if os.path.exists(local):
        with open(local, encoding="utf-8") as f:
            return f.read()
    print("downloading %s ..." % SRC[key])
    txt = urllib.request.urlopen(SRC[key], timeout=30).read().decode("utf-8")
    with open(local, "w", encoding="utf-8") as f:
        f.write(txt)
    return txt


def clean(s):
    """Map a decomp display string to plain ASCII the GBA sys8 font can render."""
    s = s.replace("♀", " F").replace("♂", " M")   # Nidoran gender
    s = s.replace("é", "E").replace("É", "E")     # POKE BALL (font is uppercase)
    s = s.replace("{POKEBLOCK}", "POKEBLOCK")
    s = re.sub(r"\{[^}]*\}", "", s)                          # strip any other macro
    s = s.strip()
    if s and all(c == "?" for c in s):                       # NONE placeholders
        s = "-"
    s = s.replace("\\", "\\\\").replace('"', '\\"')          # C-escape
    return s


def parse_named(txt, pattern):
    """Return display strings for every `pattern` match, in file (== id) order."""
    return [clean(m) for m in re.findall(pattern, txt)]


def emit_table(c, name, items):
    c.write("static const char* const %s[] = {\n" % name)
    line = "  "
    for s in items:
        tok = '"%s",' % s
        if len(line) + len(tok) > 96:
            c.write(line + "\n"); line = "  "
        line += tok
    if line.strip():
        c.write(line + "\n")
    c.write("};\n\n")


def main():
    species = parse_named(fetch("species"), r'_\("([^"]*)"\)')
    moves   = parse_named(fetch("moves"),   r'_\("([^"]*)"\)')
    items   = parse_named(fetch("items"),   r'\.name = _\("([^"]*)"\)')

    # Sanity anchors against the known internal/id layout.
    assert species[1]   == "BULBASAUR", species[1]
    assert species[404] == "KYOGRE",    species[404]   # internal 404 (icon anchor)
    assert species[411] == "CHIMECHO",  species[411]   # last displaced legendary
    assert moves[1]     == "POUND",     moves[1]
    assert items[1]     == "MASTER BALL", items[1]
    print("species:%d moves:%d items:%d" % (len(species), len(moves), len(items)))

    with open(OUT_H, "w") as h:
        h.write("/* GENERATED by tools/gen_names.py - do not edit. */\n")
        h.write("#ifndef GEN3_NAMES_H\n#define GEN3_NAMES_H\n#include <stdint.h>\n\n")
        h.write("/* Gen-3 display names. Index spaces match what the save stores:\n")
        h.write(" *   species: internal Gen-3 index (Kyogre=404), 0..%d\n" % (len(species) - 1))
        h.write(" *   move:    standard move id, 0..%d\n" % (len(moves) - 1))
        h.write(" *   item:    standard item id, 0..%d\n" % (len(items) - 1))
        h.write(" * Out-of-range ids return \"?\". All strings live in ROM. */\n")
        h.write("const char* gen3_species_name(uint16_t internal_species);\n")
        h.write("const char* gen3_move_name(uint16_t move_id);\n")
        h.write("const char* gen3_item_name(uint16_t item_id);\n\n")
        h.write("#endif\n")

    with open(OUT_C, "w") as c:
        c.write("/* GENERATED by tools/gen_names.py - do not edit. */\n")
        c.write('#include "gen3_names.h"\n\n')
        emit_table(c, "k_species", species)
        emit_table(c, "k_moves", moves)
        emit_table(c, "k_items", items)
        c.write("#define NS (sizeof(k_species)/sizeof(k_species[0]))\n")
        c.write("#define NM (sizeof(k_moves)/sizeof(k_moves[0]))\n")
        c.write("#define NI (sizeof(k_items)/sizeof(k_items[0]))\n\n")
        c.write("const char* gen3_species_name(uint16_t s){ return s < NS ? k_species[s] : \"?\"; }\n")
        c.write("const char* gen3_move_name(uint16_t m){ return m < NM ? k_moves[m] : \"?\"; }\n")
        c.write("const char* gen3_item_name(uint16_t i){ return i < NI ? k_items[i] : \"?\"; }\n")

    nbytes = sum(len(s) + 1 for s in species + moves + items)
    print("wrote %s (~%.1f KiB strings in ROM)" % (OUT_C, nbytes / 1024))


if __name__ == "__main__":
    main()
