#ifndef DATA_TABLES_H
#define DATA_TABLES_H

#include <stdint.h>

/* Gen-3 lookup tables BY NUMBER, for turning the raw ids in a decoded PkMon into
 * the names/values the game shows. The .c is GENERATED by tools/gen_data.py from
 * the pokeemerald decomp data files (authoritative Gen-3 ids) and is git-ignored
 * (generate-locally policy, same as mon_icons.c). All getters are safe for
 * out-of-range ids (return "?" / 0).
 *
 * SPECIES are keyed by the INTERNAL Gen-3 index (1..411, Hoenn-ordered) exactly
 * as stored in a mon's Growth substruct and as used by mon_icon_for(). MOVES,
 * ITEMS, ABILITIES, TYPES, NATURES, LOCATIONS use their own flat ids.
 *
 * Stat arrays use the save-native order: HP, Atk, Def, Spe, SpA, SpD (see gen3_mon.h). */

/* ---- species (by internal index) ---- */
const char* pk_species_name(uint16_t internal);
uint16_t    pk_national_no(uint16_t internal);          /* National-Dex number for "No.NNN" */
void        pk_base_stats(uint16_t internal, uint8_t out[6]);  /* HP,Atk,Def,Spe,SpA,SpD */
uint8_t     pk_species_type1(uint16_t internal);
uint8_t     pk_species_type2(uint16_t internal);
uint16_t    pk_species_ability(uint16_t internal, uint8_t ability_num); /* -> ability id */
uint8_t     pk_species_gender_ratio(uint16_t internal); /* 0=allM, 0xFE=allF, 0xFF=genderless, else female-threshold */
uint8_t     pk_species_growth(uint16_t internal);       /* growth-rate id 0..5 */

/* ---- moves (by move id) ---- */
const char* pk_move_name(uint16_t move_id);
uint8_t     pk_move_type(uint16_t move_id);
uint8_t     pk_move_pp(uint16_t move_id);               /* base PP (before PP-ups) */
uint8_t     pk_move_contest(uint16_t move_id);          /* contest category 0..4 (see pk_contest_name) */
uint8_t     pk_move_power(uint16_t move_id);            /* base power (0 = status/no power) */
uint8_t     pk_move_accuracy(uint16_t move_id);        /* accuracy % (0 = never misses) */
const char* pk_move_desc(uint16_t move_id);            /* in-game move description */

/* ---- items / abilities / natures / types / locations ---- */
const char* pk_item_name(uint16_t item_id);
const char* pk_item_desc(uint16_t item_id);             /* short item flavor text */
const char* pk_ability_name(uint16_t ability_id);
const char* pk_ability_desc(uint16_t ability_id);       /* short flavor text */
const char* pk_nature_name(uint8_t nature);             /* 0..24 */
int         pk_nature_boost(uint8_t nature);            /* stat index 1..5 boosted (×1.1), or -1 neutral */
int         pk_nature_hinder(uint8_t nature);           /* stat index 1..5 hindered (×0.9), or -1 neutral */
const char* pk_type_name(uint8_t type_id);
const char* pk_contest_name(uint8_t contest_id);        /* "Cool"/"Beauty"/"Cute"/"Smart"/"Tough" */
const char* pk_location_name(uint16_t location_id);     /* met location, e.g. "SAFARI ZONE" */

/* ---- experience / level ---- */
uint32_t    pk_exp_for_level(uint8_t growth_rate, uint8_t level);  /* exp needed AT `level` */
uint8_t     pk_level_from_exp(uint8_t growth_rate, uint32_t exp);  /* 1..100 */

#endif /* DATA_TABLES_H */
