/* GENERATED by tools/gen_names.py - do not edit. */
#ifndef GEN3_NAMES_H
#define GEN3_NAMES_H
#include <stdint.h>

/* Gen-3 display names. Index spaces match what the save stores:
 *   species: internal Gen-3 index (Kyogre=404), 0..411
 *   move:    standard move id, 0..354
 *   item:    standard item id, 0..376
 * Out-of-range ids return "?". All strings live in ROM. */
const char* gen3_species_name(uint16_t internal_species);
const char* gen3_move_name(uint16_t move_id);
const char* gen3_item_name(uint16_t item_id);

#endif
